theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
toolbar: 
  - undo redo | fullscreen | uploadimage | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link
  - preview | forecolor backcolor | fontsizeselect 
plugins:
  - table
  - fullscreen
  - uploadimage
  - textcolor 
  - colorpicker
uploadimage_form_url: '/admin/tinymce_assets'